name: example
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  htmltopdfwidgets:
    path: ../
dependency_overrides:
  archive: 3.6.1
dev_dependencies:
  flutter_lints: ^4.0.0
