name: htmltopdfwidgets
description:  Htmlt to pdf widgets library convert html text to pdf widgets
version: 0.0.8
homepage: https://github.com/alihassan143/htmltopdfwidgets

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  pdf: '>=3.10.3 <4.0.0'
  html: '>=0.15.3 <1.0.0'
  http: '>=0.13.1 <2.0.0'
dev_dependencies:
  flutter_lints: ^2.0.0
