name: htmltopdfwidgets
description: A Dart package that converts HTML and Markdown rich text content into high-quality PDF widgets. Simplify the creation of PDF documents by seamlessly transforming your structured text content into printable, professional PDFs. Perfect for generating reports, invoices, and more!
version: 2.0.1
homepage: https://github.com/alihassan143/htmltopdfwidgets

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  pdf: ">=3.11.1 <4.0.0"
  html: ">=0.15.5 <1.0.0"
  http: ">=1.2.2 <2.0.0"
  markdown: ^7.3.0
  csslib: ^1.0.2

dev_dependencies:
  flutter_lints: ^4.0.0
  lints: ^4.0.0
  test: ">=1.16.0 <2.0.0"
