name: native_pdf_engine
description: A high-performance, FFI-based Flutter package to convert HTML and URLs to PDF using native OS webviews (Android, iOS, macOS).
homepage: https://github.com/alihassan143/htmltopdfwidgets/tree/main/packages/native_pdf_engine
repository: https://github.com/alihassan143/htmltopdfwidgets/tree/main/packages/native_pdf_engine
issue_tracker: https://github.com/alihassan143/htmltopdfwidgets/issues
topics:
  - pdf
  - html-to-pdf
  - webview
  - ffi
  - jni
version: 0.0.2

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  objective_c: ^9.2.2
  ffi: ^2.1.5
  logging: ^1.3.0
  path: ^1.9.0
  jni: ^0.15.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  jnigen: ^0.15.0
  ffigen: ^20.1.1


flutter:
  plugin:
    platforms:
      ios:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      android:
        ffiPlugin: true
      windows:
        ffiPlugin: true
      linux:
        ffiPlugin: true
