name: native_pdf_engine
description: Native PDF engine using OS webviews for HTML to PDF conversion.
version: 0.0.1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  objective_c: ^9.2.2
  ffi: ^2.1.5
  logging: ^1.3.0
  path: ^1.9.0
  jni: ^0.15.2

dev_dependencies:
  flutter_lints: ^6.0.0
  jnigen: ^0.15.0
  ffigen: ^20.1.1
  test: ^1.29.0

flutter:
  plugin:
    platforms:
      ios:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      android:
        ffiPlugin: true
