name: htmltopdf_syncfusion
description: A Dart package that converts HTML and Markdown content into Syncfusion PDF.
version: 0.1.0
homepage: https://github.com/alihassan143/htmltopdfwidgets

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  syncfusion_flutter_pdf: ">=32.1.22 <40.0.0"
  html: ">=0.15.4 <1.0.0"
  http: ">=1.1.0 <2.0.0"
  markdown: ^7.1.1
  csslib: ^1.0.0
  bidi: ^2.0.13
  dartarabic: ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  assets:
    - assets/fonts/
